"""
The registered DTO type table and the type → *Definition field maps.

`dto_type` in a tweaker operation is the **decimal ObjectType as a string** —
not a message name. Sending "LedDefinition" is rejected with
`dto: DTOType not registered`. See docs/protocols/dom-tweaker.md § 6.

Field maps come from dto_definitions.json, generated by extract_dto_defs.py
from the descriptors embedded in domain-object-manager.gobin. Regenerate after
a firmware change rather than editing by hand.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve().parent
DEFINITIONS_PATH = _HERE / "dto_definitions.json"

# ObjectType number → (ObjectType.Description, *Definition message name).
#
# Enumerated on firmware 26.05.26f000 by sweeping dto_type and classifying the
# DOM log (see § 6). Descriptions are the processor's own, from the athena DB
# `ObjectType` table — two differ from the names first written down during the
# investigation: 9 is ZONE_CONTROLLER_UI (not "ZoneControlUI") and 92 is
# BUTTON_CONTROLLER (not "KeypadController").
#
# A None definition means the type is registered for tweaking but has no
# *Definition message in the DOM binary's descriptors, so this tool cannot
# build a payload for it.
REGISTERED_DTO_TYPES: dict[int, tuple[str, str | None]] = {
    2: ("AREA", "AreaDefinition"),
    3: ("SWITCH_LEG_CONTROLLER", "SwitchLegControllerDefinition"),
    4: ("CONTROL_STATION", "ControlStationDefinition"),
    5: ("CONTROL_STATION_DEVICE", "ControlStationDeviceDefinition"),
    9: ("ZONE_CONTROLLER_UI", "ZoneControllerUserInterfaceDefinition"),
    10: ("SWITCH_LEG", "SwitchLegDefinition"),
    15: ("ZONE", "ZoneDefinition"),
    32: ("LINK_NODE", "LinkNodeDefinition"),
    34: ("LINK", "LinkDefinition"),
    43: ("PRESET", "PresetDefinition"),
    44: ("PRESET_ASSIGNMENT", "PresetAssignmentDefinition"),
    46: ("PROCESSOR", "ProcessorDefinition"),
    57: ("BUTTON", "ButtonDefinition"),
    58: ("ENGRAVING_POSITION", "EngravingPositionDefinition"),
    60: ("SINGLE_ACTION_PROGRAMMING_MODEL", "SingleActionProgrammingModelDefinition"),
    74: (
        "ADVANCED_TOGGLE_PROGRAMMING_MODEL",
        "AdvancedToggleProgrammingModelDefinition",
    ),
    77: ("MASTER_RAISE_LOWER_PROGRAMMING_MODEL", None),
    92: ("BUTTON_CONTROLLER", "ButtonControllerDefinition"),
    94: ("BUTTON_GROUP", "ButtonGroupDefinition"),
    108: ("LED_CONTROLLER", "LedControllerDefinition"),
}

# Types explicitly known NOT to be registered, with why — saves re-deriving.
UNREGISTERED_NOTES: dict[int, str] = {
    107: "Led — individual LEDs cannot be tweaked; use LedController (108)",
}


class UnknownTypeError(KeyError):
    pass


@lru_cache(maxsize=1)
def _definitions() -> dict[str, Any]:
    if not DEFINITIONS_PATH.exists():
        raise FileNotFoundError(
            f"{DEFINITIONS_PATH.name} missing — regenerate with:\n"
            f"  uv run --with protobuf python {_HERE.name}/extract_dto_defs.py "
            f"<domain-object-manager.gobin> -o {DEFINITIONS_PATH.name}"
        )
    with DEFINITIONS_PATH.open() as fh:
        return json.load(fh)


def definition_name(dto_type: int) -> str:
    """The *Definition message for a registered DTO type."""
    entry = REGISTERED_DTO_TYPES.get(dto_type)
    if entry is None:
        hint = UNREGISTERED_NOTES.get(dto_type)
        raise UnknownTypeError(
            f"DTO type {dto_type} is not registered"
            + (f" ({hint})" if hint else "")
            + ". Registered: "
            + ", ".join(str(t) for t in sorted(REGISTERED_DTO_TYPES))
        )
    name = entry[1]
    if name is None:
        raise UnknownTypeError(
            f"DTO type {dto_type} ({entry[0]}) is registered for tweaking but has "
            "no *Definition message in the DOM binary's descriptors, so no "
            "payload can be built for it"
        )
    return name


def fields_for_definition(message: str) -> list[dict[str, Any]]:
    """Descriptor field entries for a *Definition message, in field order."""
    messages = _definitions()["messages"]
    if message not in messages:
        raise UnknownTypeError(
            f"no descriptor for {message}; known: {', '.join(sorted(messages))}"
        )
    return sorted(messages[message]["fields"], key=lambda f: f["number"])


def fields_for_type(dto_type: int) -> list[dict[str, Any]]:
    return fields_for_definition(definition_name(dto_type))


def type_description(dto_type: int) -> str:
    entry = REGISTERED_DTO_TYPES.get(dto_type)
    return entry[0] if entry else f"<unregistered {dto_type}>"


def table_name(dto_type: int) -> str:
    """
    The athena sqlite table holding this type's rows.

    ObjectType.Description is SCREAMING_SNAKE; the table is its PascalCase form
    with no acronym special-casing — LED_CONTROLLER is `LedController` and
    ZONE_CONTROLLER_UI is `ZoneControllerUi`.
    """
    return pascal_case(type_description(dto_type))


def pascal_case(screaming_snake: str) -> str:
    return "".join(part.capitalize() for part in screaming_snake.split("_") if part)


def column_name(proto_field: str) -> str:
    """
    The athena column backing a proto field.

    snake_case → PascalCase, with `id` capitalised as `ID`
    (`model_info_id` → `ModelInfoID`). A `*_xid` proto field is backed by the
    integer `*ID` column — the XID is looked up from the referenced row — so
    `parent_xid` → `ParentID`.
    """
    parts = proto_field.split("_")
    if parts and parts[-1] == "xid":
        parts[-1] = "id"
    out = []
    for part in parts:
        out.append("ID" if part == "id" else part.capitalize())
    return "".join(out)


def registered_table() -> list[tuple[int, str, str | None, int | None]]:
    """(type, description, definition message, field count) for display."""
    rows = []
    messages = _definitions()["messages"]
    for dto_type, (desc, msg) in sorted(REGISTERED_DTO_TYPES.items()):
        count = len(messages[msg]["fields"]) if msg and msg in messages else None
        rows.append((dto_type, desc, msg, count))
    return rows
